      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # Если gradlew лежит в подпапке, раскомментируй строку ниже и укажи имя папки:
        # working-directory: ./Имя_Папки_Проекта

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon
        # Если gradlew лежит в подпапке, раскомментируй строку ниже:
        # working-directory: ./Имя_Папки_Проекта
