name: Android Release Sign with Repo Key

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Если секреты добавлены во вкладку Environment, раскомментируй строку ниже 
    # и укажи точное название твоего окружения на GitHub (например, release):
    # environment: release

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # Тест на проверку секретов, чтобы исключить пустые строки
      - name: Check Secrets Presence
        run: |
          if [ -z "${{ secrets.KEY_ALIAS }}" ]; then echo "⚠️ ALIAS IS EMPTY!"; else echo "✅ Alias is set"; fi
          if [ -z "${{ secrets.KEYSTORE_PASSWORD }}" ]; then echo "⚠️ STORE PASSWORD IS EMPTY!"; else echo "✅ Store password is set"; fi
          if [ -z "${{ secrets.KEY_PASSWORD }}" ]; then echo "⚠️ KEY PASSWORD IS EMPTY!"; else echo "✅ Key password is set"; fi
          if [ -z "${{ secrets.KEYSTORE_BASE64 }}" ]; then echo "⚠️ BASE64 KEYSTORE IS EMPTY!"; else echo "✅ Base64 Keystore is set"; fi

  
      
      # Этап 2: Собираем
      - name: Build  Release
        run: |
          gradle assembleRelease \
            -Pandroid.injected.signing.store.file="../bytebudda.keystore" \
            -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}" \
            --no-daemon --no-configuration-cache
        working-directory: ./app

      # Переименовываем APK
      - name: Rename  APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/RuVideoHub-github.apk

      # Выгружаем оба файла в релизы GitHub
      - name: Upload APKs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/build/outputs/apk/release/RuVideoHub-github.apk
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build #${{ github.run_number }}
          draft: true
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
